[package]
name = "ms_auth_mc"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
reqwest = { version = "0.11", features = ["blocking", "json"]}
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"] }
serde_derive = "1.0"
anyhow = "1.0"